import { Injectable, OnModuleInit } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Property } from './property.entity';
import { SearchService } from '../search/search.service';

@Injectable()
export class SeedService implements OnModuleInit {
  constructor(
    @InjectRepository(Property)
    private readonly propertyRepository: Repository<Property>,
    private readonly searchService: SearchService,
  ) {}

  async onModuleInit() {
    const count = await this.propertyRepository.count();
    if (count > 0) {
      console.log('Database already seeded, skipping...');
      return;
    }

    console.log('Seeding initial commercial properties...');

    const mockProperties = [
      {
        title: 'DLF CyberPark - Tower II',
        description: 'Premium office space in DLF CyberPark with world-class amenities and infrastructure. Perfect for tech companies and corporate offices.',
        propertyType: 'Office',
        carpetArea: 8500,
        superBuiltUpArea: 10000,
        baseRent: 145,
        escalationPercent: 5,
        escalationIntervalYears: 3,
        lockInPeriodMonths: 36,
        securityDeposit: 3000000,
        maintenanceCharges: 25,
        gstNumber: '29ABCD1234F1Z5',
        isGstReady: true,
        isPowerBackup: true,
        hasLoadingDock: false,
        footfallScore: 9,
        latitude: 28.4949,
        longitude: 77.0869,
        nearbyBusinesses: [
          { name: 'Starbucks', type: 'cafe', distance: 100 },
          { name: 'ICICI Bank', type: 'bank', distance: 200 },
          { name: 'Metro Station', type: 'transit', distance: 500 }
        ],
        city: 'Gurugram',
        brokerId: null,
        brokerName: 'Rajesh Kumar',
        brokerPhone: '+91-9876543210',
        isBrokerVerified: true,
        hasFireNoc: true,
        hasOccupancyCertificate: true,
        hasParking: true,
        floor: 'Ground + 5 Floors',
        totalFloors: 6,
        furnishing: 'Fully Furnished',
        facing: 'North-East',
        cabins: 15,
        meetingRooms: 8,
        workstations: 120,
        landmark: 'Near Cyber City Metro Station',
        reraNumber: 'HRERA-1234-567-2020',
        typeSpecificAttributes: {
          floorPlateSize: 8500,
          elevatorCount: 8,
          hasCentralAc: true,
          hasFireSuppression: true,
          floorNumber: '5',
          parkingSpaces: 50,
        },
      },
      {
        title: 'Indospace Logistics Park',
        description: 'Grade A warehouse with excellent connectivity to highways. Suitable for logistics and e-commerce operations.',
        propertyType: 'Warehouse',
        carpetArea: 35000,
        superBuiltUpArea: 40000,
        baseRent: 28,
        escalationPercent: 4,
        escalationIntervalYears: 2,
        lockInPeriodMonths: 60,
        securityDeposit: 6000000,
        maintenanceCharges: 15,
        gstNumber: '29ABCD5678F1Z5',
        isGstReady: true,
        isPowerBackup: true,
        hasLoadingDock: true,
        footfallScore: 7,
        latitude: 28.4211,
        longitude: 77.0448,
        nearbyBusinesses: [
          { name: 'Highway Exit', type: 'transit', distance: 50 },
          { name: 'Fuel Station', type: 'amenity', distance: 200 }
        ],
        city: 'Gurugram',
        brokerId: null,
        brokerName: 'Priya Sharma',
        brokerPhone: '+91-9876543211',
        isBrokerVerified: true,
        hasFireNoc: true,
        hasOccupancyCertificate: true,
        hasParking: true,
        floor: 'Ground Floor',
        totalFloors: 1,
        furnishing: 'Semi-Furnished',
        facing: 'South',
        cabins: 2,
        meetingRooms: 4,
        workstations: 0,
        landmark: 'Near NH-48 Highway',
        reraNumber: 'HRERA-2345-678-2020',
        typeSpecificAttributes: {
          dockHeight: 12,
          loadingDocks: 4,
          hasSprinklerSystem: true,
          hasColdStorage: false,
          truckTurningRadius: 45,
          ceilingHeight: 32,
        },
      },
      {
        title: 'Phoenix Marketcity Retail',
        description: 'Premium retail space in Phoenix Marketcity with high footfall. Ideal for fashion, electronics, or F&B brands.',
        propertyType: 'Retail',
        carpetArea: 1800,
        superBuiltUpArea: 2000,
        baseRent: 380,
        escalationPercent: 7,
        escalationIntervalYears: 3,
        lockInPeriodMonths: 60,
        securityDeposit: 6000000,
        maintenanceCharges: 40,
        gstNumber: '27ABCD9012F1Z5',
        isGstReady: true,
        isPowerBackup: true,
        hasLoadingDock: false,
        footfallScore: 10,
        latitude: 19.0859,
        longitude: 72.8814,
        nearbyBusinesses: [
          { name: 'Phoenix Mall', type: 'mall', distance: 0 },
          { name: 'Kurla Station', type: 'transit', distance: 300 },
          { name: 'Multiple Restaurants', type: 'restaurant', distance: 100 }
        ],
        city: 'Mumbai',
        brokerId: null,
        brokerName: 'Amit Patel',
        brokerPhone: '+91-9876543212',
        isBrokerVerified: true,
        hasFireNoc: true,
        hasOccupancyCertificate: true,
        hasParking: true,
        floor: '1st Floor',
        totalFloors: 4,
        furnishing: 'Unfurnished',
        facing: 'East',
        cabins: 0,
        meetingRooms: 1,
        workstations: 0,
        landmark: 'Near Kurla West Station',
        reraNumber: 'MHARA-3456-789-2020',
        typeSpecificAttributes: {
          frontageWidth: 45,
          footfall: 25000,
          hasCornerLocation: true,
          anchorTenant: true,
          storefrontType: 'Mall',
        },
      },
      {
        title: 'WeWork Galaxy - Premium Co-Working',
        description: 'Modern co-working space with flexible seating options. Perfect for startups and growing teams.',
        propertyType: 'CoWorking',
        carpetArea: 5000,
        superBuiltUpArea: 6000,
        baseRent: 95,
        escalationPercent: 6,
        escalationIntervalYears: 2,
        lockInPeriodMonths: 24,
        securityDeposit: 2000000,
        maintenanceCharges: 30,
        gstNumber: '29ABCD3456F1Z5',
        isGstReady: true,
        isPowerBackup: true,
        hasLoadingDock: false,
        footfallScore: 8,
        latitude: 12.9716,
        longitude: 77.5946,
        nearbyBusinesses: [
          { name: 'MG Road Metro', type: 'transit', distance: 200 },
          { name: 'Multiple Cafes', type: 'cafe', distance: 50 },
          { name: 'Tech Companies', type: 'office', distance: 100 }
        ],
        city: 'Bangalore',
        brokerId: null,
        brokerName: 'Sneha Reddy',
        brokerPhone: '+91-9876543213',
        isBrokerVerified: true,
        hasFireNoc: true,
        hasOccupancyCertificate: true,
        hasParking: true,
        floor: 'Ground + 3 Floors',
        totalFloors: 4,
        furnishing: 'Fully Furnished',
        facing: 'North',
        cabins: 10,
        meetingRooms: 12,
        workstations: 200,
        landmark: 'Residency Road',
        reraNumber: 'KARA-4567-890-2020',
        typeSpecificAttributes: {
          privateCabins: 10,
          hotDesks: 150,
          meetingRooms: 12,
          hasPhoneBooths: true,
          hasEventSpace: true,
          includedAmenities: 'Coffee,Snacks,Printing,Reception,Security',
        },
      },
      {
        title: 'Tech Boulevard - IT SEZ',
        description: 'SEZ office space with tax benefits. Under construction, possession in 6 months.',
        propertyType: 'Office',
        carpetArea: 12000,
        superBuiltUpArea: 15000,
        baseRent: 210,
        escalationPercent: 5,
        escalationIntervalYears: 3,
        lockInPeriodMonths: 48,
        securityDeposit: 4000000,
        maintenanceCharges: 22,
        gstNumber: '27ABCD7890F1Z5',
        isGstReady: false,
        isPowerBackup: true,
        hasLoadingDock: false,
        footfallScore: 7,
        latitude: 18.5679,
        longitude: 73.7333,
        nearbyBusinesses: [
          { name: 'Hinjewadi IT Park', type: 'office', distance: 100 },
          { name: 'Food Court', type: 'restaurant', distance: 200 }
        ],
        city: 'Pune',
        brokerId: null,
        brokerName: 'Vikram Singh',
        brokerPhone: '+91-9876543214',
        isBrokerVerified: false,
        hasFireNoc: true,
        hasOccupancyCertificate: false,
        hasParking: true,
        floor: 'Ground + 8 Floors',
        totalFloors: 9,
        furnishing: 'Shell Condition',
        facing: 'West',
        cabins: 20,
        meetingRooms: 15,
        workstations: 300,
        landmark: 'Hinjewadi Phase 3',
        reraNumber: 'PUNERA-5678-901-2020',
        typeSpecificAttributes: {
          floorPlateSize: 12000,
          elevatorCount: 12,
          hasCentralAc: true,
          hasFireSuppression: true,
          floorNumber: 'Ground',
          parkingSpaces: 80,
        },
      },
      {
        title: 'Ambience Mall - Premium Retail',
        description: 'Flagship retail location in South Delhi\'s premier mall. Maximum brand visibility.',
        propertyType: 'Retail',
        carpetArea: 2200,
        superBuiltUpArea: 2500,
        baseRent: 425,
        escalationPercent: 8,
        escalationIntervalYears: 3,
        lockInPeriodMonths: 72,
        securityDeposit: 6000000,
        maintenanceCharges: 45,
        gstNumber: '07ABCD1234F1Z5',
        isGstReady: true,
        isPowerBackup: true,
        hasLoadingDock: false,
        footfallScore: 10,
        latitude: 28.5244,
        longitude: 77.1589,
        nearbyBusinesses: [
          { name: 'Ambience Mall', type: 'mall', distance: 0 },
          { name: 'Multiple Brands', type: 'retail', distance: 50 },
          { name: 'NH-8 Highway', type: 'transit', distance: 100 }
        ],
        city: 'New Delhi',
        brokerId: null,
        brokerName: 'Neha Gupta',
        brokerPhone: '+91-9876543215',
        isBrokerVerified: true,
        hasFireNoc: true,
        hasOccupancyCertificate: true,
        hasParking: true,
        floor: 'Ground Floor',
        totalFloors: 3,
        furnishing: 'Unfurnished',
        facing: 'North',
        cabins: 0,
        meetingRooms: 1,
        workstations: 0,
        landmark: 'Near Vasant Kunj',
        reraNumber: 'DLRERA-6789-012-2020',
        typeSpecificAttributes: {
          frontageWidth: 60,
          footfall: 35000,
          hasCornerLocation: true,
          anchorTenant: true,
          storefrontType: 'Mall',
        },
      },
      {
        title: 'Global Industrial Hub - Chennai',
        description: 'Massive industrial hub with state-of-the-art infrastructure. Ideal for manufacturing plants and large-scale distribution centers.',
        propertyType: 'Industrial',
        carpetArea: 100000,
        superBuiltUpArea: 120000,
        baseRent: 35,
        escalationPercent: 5,
        escalationIntervalYears: 3,
        lockInPeriodMonths: 60,
        securityDeposit: 6000000,
        maintenanceCharges: 10,
        gstNumber: '33ABCD5678F1Z5',
        isGstReady: true,
        isPowerBackup: true,
        hasLoadingDock: true,
        footfallScore: 5,
        latitude: 12.9244,
        longitude: 79.8689,
        nearbyBusinesses: [
          { name: 'Sriperumbudur Industrial Area', type: 'industrial', distance: 100 },
          { name: 'Chennai Port', type: 'logistics', distance: 5000 },
          { name: 'Highway Access', type: 'transit', distance: 200 }
        ],
        city: 'Chennai',
        brokerId: null,
        brokerName: 'Karthik Rajan',
        brokerPhone: '+91-9876543216',
        isBrokerVerified: true,
        hasFireNoc: true,
        hasOccupancyCertificate: true,
        hasParking: true,
        floor: 'Ground Floor',
        totalFloors: 1,
        furnishing: 'Semi-Furnished',
        facing: 'South-East',
        cabins: 5,
        meetingRooms: 3,
        workstations: 0,
        landmark: 'Sriperumbudur',
        reraNumber: 'TNREA-7890-123-2020',
        typeSpecificAttributes: {
          powerCapacity: 500,
          hasHeavyMachineryAccess: true,
          hasEffluentTreatment: true,
          zoneType: 'SEZ',
          craneCapacity: 25,
        },
      }
    ];

    try {
      const savedProperties = await this.propertyRepository.save(mockProperties as any);
      console.log('✅ Successfully seeded 7 commercial properties');
      
      // Index properties in Meilisearch
      await this.searchService.indexProperties(savedProperties);
      console.log('✅ Successfully indexed properties in Meilisearch');
    } catch (e) {
      console.error('❌ Seeding failed:', e);
    }
  }
}
